DROP TRIGGER IF EXISTS finding_citations_count ON finding_citations;
DROP TRIGGER IF EXISTS findings_citation_count ON findings;
DROP FUNCTION IF EXISTS assert_finding_citation_count();
DROP TRIGGER IF EXISTS assurance_runs_immutable_pins ON assurance_runs;
DROP FUNCTION IF EXISTS assurance_runs_immutable_pins();
DROP TRIGGER IF EXISTS assurance_runs_match_grant ON assurance_runs;
DROP FUNCTION IF EXISTS assurance_runs_match_grant();
DROP TRIGGER IF EXISTS authorisation_grants_guard ON authorisation_grants;
DROP FUNCTION IF EXISTS authorisation_grants_guard();
DROP TRIGGER IF EXISTS events_append_only ON events;
DROP TRIGGER IF EXISTS finding_citations_append_only ON finding_citations;
DROP TRIGGER IF EXISTS findings_append_only ON findings;
DROP TRIGGER IF EXISTS observations_append_only ON observations;
DROP TRIGGER IF EXISTS profile_versions_append_only ON profile_versions;
DROP FUNCTION IF EXISTS reject_append_only();
DROP TABLE IF EXISTS outbox;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS cases;
DROP TABLE IF EXISTS finding_citations;
DROP TABLE IF EXISTS findings;
DROP TABLE IF EXISTS observations;
DROP TABLE IF EXISTS run_steps;
DROP TABLE IF EXISTS assurance_runs;
DROP TABLE IF EXISTS authorisation_grants;
DROP TABLE IF EXISTS profile_versions;
